### ISSUE TITLE
Measure is a tad wide

### ISSUE THREAD

**Issue by mrmrs** [donnieberg/portfolio#1]
Hey!

I've noticed some of the body copy has a measure that is a little wider than ideal.
Generally you want to be within 45-75 characters.

On desktop this at full-width is 92 characters wide:
"I started working as a developer in 2013. Prior to that, I was an Event Planner at the KIPP"

You could potentially reduce the measure by creating a single purpose class that sets max-width to something between 28-30em.

**Comment by donnieberg** [comment]
Thanks so much for flagging this! I didn't realize spaces were included but now I've fixed it so that the longest line is 73 chars.
