### ISSUE TITLE
Sass not SASS

### ISSUE THREAD

**Issue by TheJaredWilcurt** [donnieberg/portfolio#2]
#### [SassNotSASS.com](http://sassnotsass.com)

Sass is the name of the meta-language it has no acronym and isn't an abbreviation.

Its filetypes do have meaning:
- `.scss` = Sassy CSS
- `.sass` = Syntactically Awesome Style Sheets

When referring to the language, use `Sass`, when referring to the files use `.scss`, `.sass`, `SCSS files`, or `SASS files`. However it's not recommend to use `SASS files` (meaning only .sass files) as it could be easily confused with `Sass files` (meaning all files specific to the Sass meta-language).

**Comment by donnieberg** [comment]
oh man! How did I miss this issue? Thanks for letting me know. I updated the copy.
